export const userList = [
    {
      "id": 1,"firstName": "John",
      "lastName": "Doe",
      "email": "john.doe@example.com",
      "phone": "123-456-7890",
      "dob": "1990-01-15",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/men/1.jpg",
      "isAdmin": false,
      "isDeleted": false,
      "address": "123 Main St, New York, NY 10001"
    },
    {
      "id": 2,"firstName": "Jane",
      "lastName": "Smith",
      "email": "jane.smith@example.com",
      "phone": "234-567-8901",
      "dob": "1985-05-20",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/women/2.jpg",
      "isAdmin": true,
      "isDeleted": false,
      "address": "456 Oak St, San Francisco, CA 94102"
    },
    {
      "id": 3,"firstName": "Michael",
      "lastName": "Johnson",
      "email": "michael.johnson@example.com",
      "phone": "345-678-9012",
      "dob": "1992-08-25",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/men/3.jpg",
      "isAdmin": false,
      "isDeleted": false,
      "address": "789 Pine St, Los Angeles, CA 90003"
    },
    {
      "id": 4,"firstName": "Emily",
      "lastName": "Davis",
      "email": "emily.davis@example.com",
      "phone": "456-789-0123",
      "dob": "1994-12-30",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/women/4.jpg",
      "isAdmin": true,
      "isDeleted": true,
      "address": "101 Maple St, Chicago, IL 60604"
    },
    
    {
      "id": 5,"firstName": "Olivia",
      "lastName": "Garcia",
      "email": "olivia.garcia@example.com",
      "phone": "678-901-2345",
      "dob": "1995-06-15",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/women/6.jpg",
      "isAdmin": false,
      "isDeleted": true,
      "address": "303 Cedar St, Phoenix, AZ 85006"
    },
    {
      "id": 6,"firstName": "James",
      "lastName": "Rodriguez",
      "email": "james.rodriguez@example.com",
      "phone": "789-012-3456",
      "dob": "1991-09-20",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/men/7.jpg",
      "isAdmin": true,
      "isDeleted": false,
      "address": "404 Elm St, Philadelphia, PA 19107"
    },
    {
      "id": 7,"firstName": "Sophia",
      "lastName": "Wilson",
      "email": "sophia.wilson@example.com",
      "phone": "890-123-4567",
      "dob": "1987-11-05",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/women/8.jpg",
      "isAdmin": false,
      "isDeleted": false,
      "address": "505 Spruce St, San Antonio, TX 78208"
    },
    {
      "id": 8,"firstName": "Daniel",
      "lastName": "Anderson",
      "email": "daniel.anderson@example.com",
      "phone": "901-234-5678",
      "dob": "1983-04-18",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/men/9.jpg",
      "isAdmin": false,
      "isDeleted": true,
      "address": "606 Walnut St, Dallas, TX 75209"
    },
    {
      "id": 9,"firstName": "Mia",
      "lastName": "Thomas",
      "email": "mia.thomas@example.com",
      "phone": "012-345-6789",
      "dob": "1999-07-25",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/women/10.jpg",
      "isAdmin": true,
      "isDeleted": false,
      "address": "707 Chestnut St, San Jose, CA 95110"
    },
    {
      "id": 10,"firstName": "William",
      "lastName": "Taylor",
      "email": "william.taylor@example.com",
      "phone": "123-456-7891",
      "dob": "1993-02-14",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/men/11.jpg",
      "isAdmin": false,
      "isDeleted": false,
      "address": "808 Redwood St, Austin, TX 78711"
    },
    {
      "id": 11,"firstName": "Isabella",
      "lastName": "Harris",
      "email": "isabella.harris@example.com",
      "phone": "234-567-8902",
      "dob": "1996-10-12",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/women/12.jpg",
      "isAdmin": true,
      "isDeleted": false,
      "address": "909 Willow St, Jacksonville, FL 32212"
    },
    {
      "id": 12,"firstName": "Alexander",
      "lastName": "Lee",
      "email": "alexander.lee@example.com",
      "phone": "345-678-9013",
      "dob": "1982-01-28",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/men/13.jpg",
      "isAdmin": false,
      "isDeleted": true,
      "address": "1010 Sycamore St, Indianapolis, IN 46213"
    },
    {
      "id": 13,"firstName": "Ava",
      "lastName": "Walker",
      "email": "ava.walker@example.com",
      "phone": "456-789-0124",
      "dob": "1997-05-30",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/women/14.jpg",
      "isAdmin": false,
      "isDeleted": false,
      "address": "1111 Poplar St, Columbus, OH 43214"
    },
    {
      "id": 14,"firstName": "Henry",
      "lastName": "Young",
      "email": "henry.young@example.com",
      "phone": "567-890-1235",
      "dob": "1986-12-19",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/men/15.jpg",
      "isAdmin": true,
      "isDeleted": false,
      "address": "1212 Fir St, Fort Worth, TX 76115"
    },
    {
      "id": 15,"firstName": "David",
      "lastName": "Martinez",
      "email": "david.martinez@example.com",
      "phone": "567-890-1234",
      "dob": "1988-03-10",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/men/5.jpg",
      "isAdmin": false,
      "isDeleted": false,
      "address": "202 Birch St, Houston, TX 77005"
    },
    {
      "id": 16,"firstName": "Charlotte",
      "lastName": "King",
      "email": "charlotte.king@example.com",
      "phone": "678-901-2346",
      "dob": "1998-07-21",
      "age": 0,
      "profileImageUrl": "https://randomuser.me/api/portraits/women/16.jpg",
      "isAdmin": false,
      "isDeleted": true,
      "address": "1313 Pine St, Charlotte, NC 28216"
    }
  ]